# Generated by scripts/update-packaging.sh for v0.1.0; do not edit by hand.
class Clift < Formula
  desc "Paste a screenshot into the coding agent running on your server"
  homepage "https://github.com/leazoot/clift"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "d0b33d1db22fb2bd13212a33af9caff9aa7c3ef6172b25822b7d8b3209327634"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "10dd1c3f05eff166991e0e3d9ecb6b785ddd6ef6ee96fc2c87448b984d6fa36e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d0dff15c69fa06f939e55c5343e639323b96957bbd2533115ec0ff3b85980dd3"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "f1635058aac024c7ca38017732fd926a3f76a4e8e99d9b924ed74aa6591c6d14"
    end
  end

  def install
    bin.install "clift"
    bin.install "clift-relayd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clift --version")
  end
end
