# Generated by scripts/update-packaging.sh for v0.1.7; do not edit by hand.
class Clift < Formula
  desc "Paste a screenshot into the coding agent running on your server"
  homepage "https://github.com/leazoot/clift"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.7/clift-0.1.7-aarch64-apple-darwin.tar.gz"
      sha256 "3cc42de6ba46ea996d865554831d7e13d38e382d799b420679f383602418ed68"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.7/clift-0.1.7-x86_64-apple-darwin.tar.gz"
      sha256 "d769e1aee3d593e83d1662cb2257eb149ed20349025e29ea993f68ca3f434757"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.7/clift-0.1.7-aarch64-unknown-linux-musl.tar.gz"
      sha256 "f668eb3b43c2ef38037254bd2a5e72406ecd396eb48c3ddaf299a4026dc9e340"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.7/clift-0.1.7-x86_64-unknown-linux-musl.tar.gz"
      sha256 "e9b1d53bdafa2fd4f304943bb8d8190ee52dd3c21378a5f77dea5f06ad5dbc1b"
    end
  end

  def install
    bin.install "clift"
    bin.install "clift-relayd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clift --version")
  end
end
