# Generated by scripts/update-packaging.sh for v0.1.0; do not edit by hand.
class Clift < Formula
  desc "Paste a screenshot into the coding agent running on your server"
  homepage "https://github.com/leazoot/clift"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "cd6800ba26211efcf42859df444627f3b3a559a269f9896ca8f5bbdbf2a4587a"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "c0a25af05853cf2d694c75f45c5d8fe7b05352a79b22a563311e528462a49244"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "fc8998333c5133085b4c47c5a417a07b2395e16908a32fb71e87c3b749464b2d"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.0/clift-0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b54f5aa5f65d761df1228037beb43545e7aefb0f15a362281ed47a17085dbf4f"
    end
  end

  def install
    bin.install "clift"
    bin.install "clift-relayd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clift --version")
  end
end
